# Generated by Django 3.2.10 on 2021-12-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('point', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('birth', models.DateField()),
            ],
        ),
    ]
